name: tools.deps-builder
uses: vouch-opensource/tools.deps-build@1.0.1
with:
  # The alias or concatenated aliases (eg test, mem:test, ...)
  alias: # default is test
  # Any java opts (eg -Xmx512m)
  java-opts: # optional
  # GitHub secret with the SSH private key to access your private repositories
  ssh-key: # optional
  # Working directoy in which to execute the clojure command
  working-directory: # optional

-----------------------------------------------------
 
steps:
- uses: actions/checkout@latest
// The JDK version to make available on the path. Required to run any clojure command line tools.
// You can use any package that providing any JDK here, eg. `actions/setup-java@v1`
// or you can use mine package to provision graalvm on hosted environment.
- uses: DeLaGuardo/setup-graalvm@2.0
  with:
    graalvm-version: '19.3.1.java11'
- uses: DeLaGuardo/setup-clojure@2.0
  with:
    tools-deps: '1.10.1.469'
- run: clojure -Sdescribe

---------------------------------------------------
  
steps:
- uses: actions/checkout@v1
- uses: DeLaGuardo/clojure-lint-action@v1
  with:
    clj-kondo-args: --lint src
    # secrets.GITHUB_TOKEN is needed here
    # to publish annotations back to github
    # this action is not storing or sending it anywhere
    github_token: ${{ secrets.GITHUB_TOKEN }}

---------------------------------------------------

name: Clojure CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: lein deps
    - name: Run tests
      run: lein test
