name: tools.deps builder

on: push
jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    container: clojure:tools-deps
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Smoke test (Run 'clojure -Sdescribe')
        run: clojure -Sdescribe
