name: tools.deps builder

on: push
jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: (Smoke) Build with Clojure CLI
        uses: docker://clojure:tools-deps
      - name: Run 'clojure -Sdescribe'
        run: clojure -Sdescribe
